name: CI

on:
  push: {}
  schedule:
  - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update
      run: |
        gh_actor_profile="$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/users/${GITHUB_ACTOR}")"
        git config --global user.name "$(printf '%s' "$gh_actor_profile" | jq -r .name)"
        git config --global user.email "$(printf '%s' "$gh_actor_profile" | jq -r .email)"
        gh_url=$(git ls-remote --get-url)
        git remote set-url origin ${gh_url/:\/\//:\/\/$GITHUB_TOKEN@}
        echo $(git ls-remote --get-url)
        git config --list
        chmod +x update.sh
        ./update.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
