name: CI2

on:
  push: {}
  schedule:
  - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name "YTT Bot"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        if [ ! -f po13.txt ]; then
          echo x > po13.txt
          git add .
          git commit -m 'po13'
          git push -u origin master
        fi
