name: CI2

on:
  push: {}
  schedule:
  - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name "YTT Bot"
        git config user.email "000-00-9${GITHUB_ACTOR}@users.noreply.github.com"
        if [ ! -f po134.txt ]; then
          echo x > po134.txt
          git add .
          git commit -m 'po134'
          git push -u origin master
        fi
