name: CI

on:
  push: {}
  schedule:
  - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: master
    - name: Update
      run: |
        chmod +x test.sh
        ./test.sh
        git checkout master
        git config -l
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
