name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update
      run: |
        chmod +x update.sh
        ./update.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
